[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx turbo run build --filter=web"]

[start]
cmd = "npx serve -s apps/web/dist -p 3000"

[variables]
VITE_SUPABASE_URL = "https://supabase.yedirenklicinar.digitalalem.com"
